version: "3.9"
services:

  pd-backend:
    container_name: "local-pd-backend"
    build:
      context: "../../"
      dockerfile: "./posts-dump-backend/Dockerfile"
    volumes:
      - "local-pd-backend_vol:/var/app"
    depends_on:
      pd-requests-queue:
        condition: "service_healthy"
      pd-buckets-storage:
        condition: "service_healthy"
      pd-notifications:
        condition: "service_healthy"
    env_file: ".env"

  pd-requests-queue:
    container_name: "local-pd-requests-queue"
    image: "rabbitmq:3.12.6-management-alpine"
    volumes:
      - "local-pd-requests-queue_vol:/var/lib/rabbitmq"
    hostname: "pd-requests-queue"
    expose:
      - "5672"
    ports:
      - "15672:15672"
    healthcheck:
      test: "rabbitmq-diagnostics -q check_running"
      start_period: 5s
      interval: 2s
      retries: 20
      timeout: 5s

  pd-buckets-storage:
    container_name: "local-pd-buckets-storage"
    image: "minio/minio:RELEASE.2023-09-23T03-47-50Z"
    command: server --console-address ":9001" /data
    volumes:
      - "local-pd-buckets-storage_vol:/data"
    hostname: "pd-buckets-storage"
    expose:
      - "9000"
    ports:
      - "9001:9001"
    healthcheck:
      test: "curl -f http://pd-buckets-storage:9000/minio/health/live || exit 1"
      interval: 2s
      retries: 20
      timeout: 5s

  pd-notifications:
    container_name: "local-pd-notifications"
    image: "bitnami/kafka:3.6.0-debian-11-r0"
    volumes:
      - "local-pd-notifications_vol:/bitnami/kafka"
    hostname: "pd-notifications"
    expose:
      - "9092"
    environment:
      - "KAFKA_CFG_NODE_ID=0"
      - "KAFKA_CFG_PROCESS_ROLES=controller,broker"
      - "KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@pd-notifications:9093"
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092"
      - "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      - "KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER"
      - "KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT"
    healthcheck:
      test: "kafka-topics.sh --bootstrap-server pd-notifications:9092 --list"
      interval: 2s
      retries: 20
      timeout: 5s

volumes:
  local-pd-backend_vol:
  local-pd-requests-queue_vol:
  local-pd-buckets-storage_vol:
  local-pd-notifications_vol:

networks:
  default:
    name: "local-pd-platform_net"