/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */

plugins {
    application
    kotlin("jvm")
    id("com.google.devtools.ksp")
    id("org.jlleitschuh.gradle.ktlint")
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

group = "pl.gleosys.postsdump"
version = "0.0.1-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    /* Core */
    implementation(libs.guice)
    implementation(libs.arrowCore)
    implementation(libs.arrowCoroutines)
    implementation(libs.fuel)
    implementation(libs.fuelMoshi)
    implementation(libs.moshi)
    implementation(libs.moshiAdapters)
    implementation(libs.kotlinLoggingJVM)
    implementation(libs.slf4j)

    /* Infrastructure */
    implementation(libs.amqpClient)
    implementation(libs.awsSDKS3)
    implementation(libs.awsSDKUrlConnectionClient)
    implementation(libs.logback)

    /* Tests */
    testImplementation(libs.kotlinTestJunit5)
    testImplementation(libs.junitJupiterEngine)
    testRuntimeOnly(libs.junitPlatformLauncher)

    ksp(libs.moshiKotlinCodegen)
}

kotlin {
    jvmToolchain(17)
}

application {
    mainClass.set("pl.gleosys.postsdump.MainKt")
}

ktlint {
    filter {
        // BUG: pattern '**/generated/**' does not work
        exclude { entry -> entry.file.toString().contains("generated") }
        include("**/kotlin/**")
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

tasks.withType<Jar> {
    manifest { attributes("Main-Class" to "pl.gleosys.postsdump.MainKt") }
}
